services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes:
      - /opt/adguard/work/:/opt/adguardhome/work
      - /opt/adguard/conf/:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:80/tcp"
